#!/usr/bin/env -S uv run --script
#MISE description="Bump minimum Python version in project files"
# /// script
# dependencies = [
#     "packaging",
# ]
# ///
from pathlib import Path

from packaging.version import Version

python_version_path = Path(".python-version")
old_version_string = python_version_path.read_text().strip()
old_version = Version(old_version_string)
new_version_string = f"{old_version.major}.{old_version.minor + 1}"
python_version_path.write_text(new_version_string + "\n")

tests_workflow_path = Path(".github/workflows/tests.yml")
tests_workflow = tests_workflow_path.read_text()
tests_workflow = tests_workflow.replace(
    f'"{old_version_string}"]',
    f'"{old_version_string}", "{new_version_string}"]',
)
tests_workflow = tests_workflow.replace(
    f"matrix.python == '{old_version_string}'",
    f"matrix.python == '{new_version_string}'",
)
tests_workflow_path.write_text(tests_workflow)

scrutinizer_config_path = Path(".scrutinizer.yml")
if scrutinizer_config_path.exists():
    scrutinizer_config = scrutinizer_config_path.read_text()
    scrutinizer_config = scrutinizer_config.replace(
        old_version_string,
        new_version_string,
    )
    scrutinizer_config_path.write_text(scrutinizer_config)

pyproject_path = Path("pyproject.toml")
pyproject_text = pyproject_path.read_text()
old_str = f'    "Programming Language :: Python :: {old_version_string}",\n'
new_str = f'    "Programming Language :: Python :: {new_version_string}",\n'
pyproject_text = pyproject_text.replace(
    old_str,
    old_str + new_str,
)
pyproject_path.write_text(pyproject_text)

print(f"Bumped Python {old_version_string} -> {new_version_string}")
