"""BiasField: simulate MRI B1 field inhomogeneity.

Uses the SynthSeg approach (Billot et al.): sample a small random tensor,
trilinearly upsample to image size, exponentiate, and multiply. Pure
PyTorch, GPU-native, and differentiable.
"""

from __future__ import annotations

from typing import Any

import torch
import torch.nn.functional as functional
from torch import Tensor

from ..data.batch import SubjectsBatch
from .parameter_range import to_nonneg_range
from .transform import IntensityTransform


class BiasField(IntensityTransform):
    r"""Corrupt an image with a smooth multiplicative bias field.

    The bias field is generated by:

    1. Sampling a small 3D tensor from $\mathcal{N}(0, \sigma)$.
    2. Trilinearly upsampling it to the image spatial shape.
    3. Taking the voxel-wise exponential to make it strictly positive.
    4. Multiplying the image by the resulting field.

    This follows the approach used in [SynthSeg: Segmentation of brain MRI
    scans of any contrast and resolution without
    retraining](https://www.sciencedirect.com/science/article/pii/S1361841523000506).

    Args:
        std: Standard deviation $\sigma$ of the normal distribution
            used to sample the coarse bias field. Larger values produce
            stronger inhomogeneity. If two values $(a, b)$ are provided,
            $\sigma \sim \mathcal{U}(a, b)$. A
            ``torch.distributions.Distribution`` may also be passed.
        scale: Ratio between the coarse field size and the image spatial
            shape. Smaller values produce smoother fields.
        **kwargs: See [`Transform`][torchio.Transform].

    Examples:
        >>> import torchio as tio
        >>> transform = tio.BiasField()
        >>> transform = tio.BiasField(std=0.8)
        >>> transform = tio.BiasField(std=(0.0, 1.0))
    """

    def __init__(
        self,
        *,
        std: float | tuple[float, float] | torch.distributions.Distribution = 0.5,
        scale: float = 0.025,
        **kwargs: Any,
    ) -> None:
        super().__init__(**kwargs)
        self.std = to_nonneg_range(std)
        if scale <= 0 or scale > 1:
            msg = f"scale must be in (0, 1], got {scale}"
            raise ValueError(msg)
        self.scale = scale

    def make_params(self, batch: SubjectsBatch) -> dict[str, Any]:
        """Sample the bias field standard deviation and a random seed."""
        return {
            "std": self.std.sample_1d(),
            "seed": int(torch.randint(0, 2**31, (1,)).item()),
            "scale": self.scale,
        }

    def apply_transform(
        self,
        batch: SubjectsBatch,
        params: dict[str, Any],
    ) -> SubjectsBatch:
        """Multiply each selected image by a smooth random bias field."""
        std = params["std"]
        seed = params["seed"]
        scale = params["scale"]

        if std == 0:
            return batch

        for _name, img_batch in self._get_images(batch).items():
            field = _generate_bias_field(
                img_batch.data.shape,
                std=std,
                scale=scale,
                seed=seed,
                device=img_batch.data.device,
            )
            img_batch.data = img_batch.data * field

        return batch

    @property
    def invertible(self) -> bool:
        """Whether this transform can be inverted."""
        return True

    def inverse(self, params: dict[str, Any]) -> _BiasFieldInverse:
        """Build the inverse by dividing by the same bias field."""
        return _BiasFieldInverse(
            std=params["std"],
            seed=params["seed"],
            scale=params["scale"],
            copy=False,
        )


class _BiasFieldInverse(IntensityTransform):
    """Inverse of BiasField for history replay."""

    def __init__(
        self,
        *,
        std: float,
        seed: int,
        scale: float,
        **kwargs: Any,
    ) -> None:
        super().__init__(**kwargs)
        self._std = std
        self._seed = seed
        self._scale = scale

    def make_params(self, batch: SubjectsBatch) -> dict[str, Any]:
        """Return empty params; all state is in instance attributes."""
        return {}

    def apply_transform(
        self,
        batch: SubjectsBatch,
        params: dict[str, Any],
    ) -> SubjectsBatch:
        """Divide by the regenerated bias field."""
        if self._std == 0:
            return batch

        for _name, img_batch in self._get_images(batch).items():
            field = _generate_bias_field(
                img_batch.data.shape,
                std=self._std,
                scale=self._scale,
                seed=self._seed,
                device=img_batch.data.device,
            )
            img_batch.data = img_batch.data / field

        return batch


def _generate_bias_field(
    shape: tuple[int, ...],
    *,
    std: float,
    scale: float,
    seed: int,
    device: torch.device,
) -> Tensor:
    """Generate a smooth multiplicative bias field.

    Args:
        shape: ``(B, C, I, J, K)`` tensor shape.
        std: Standard deviation of the normal distribution.
        scale: Ratio between the coarse field and the spatial shape.
        seed: Random seed for reproducibility.
        device: Device to create the field on.

    Returns:
        ``(B, C, I, J, K)`` bias field (strictly positive).
    """
    batch_size, channels = shape[0], shape[1]
    spatial = shape[2:]
    # Compute the coarse field shape (at least 4 per axis for interpolation).
    small_shape = [max(round(s * scale), 4) for s in spatial]

    generator = torch.Generator(device="cpu")
    generator.manual_seed(seed)

    # Sample on CPU for reproducibility, then move to device.
    small_field = torch.normal(
        mean=0.0,
        std=std,
        size=(batch_size, channels, *small_shape),
        generator=generator,
    ).to(device)

    # Trilinearly upsample to full spatial size.
    field = functional.interpolate(
        small_field,
        size=list(spatial),
        mode="trilinear",
        align_corners=True,
    )

    # Exponentiate to make strictly positive.
    return torch.exp(field)
