name: Publish

on: push

jobs:
  build:
    name: Build the package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Build a binary wheel and a source tarball
      run: uv build

    - name: Upload dist directory
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist

  publish:
    name: Publish the package
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Print ref
        run: echo ${{ github.ref }}

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Publish package to TestPyPI
        run: uv publish --publish-url https://test.pypi.org/legacy/

      - name: Publish package to PyPI if commit is tagged
        # Publish only tagged commits
        if: startsWith(github.ref, 'refs/tags')
        run: uv publish
