name: Publish

on: push

permissions:
  id-token: write

jobs:
  Build-and-publish:
    name: Build and publish if needed
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Publish TorchIO to TestPyPI
      uses: ./.github/actions/publish-package
      with:
        test: true

    # Publish only tagged commits
    - name: Publish TorchIO to PyPI if commit is tagged
      if: startsWith(github.ref, 'refs/tags')
      uses: ./.github/actions/publish-package
      with:
        test: false
