name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  pytest:
    name: Unit tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.10", "3.11", "3.12", "3.13", "3.14"]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}
      UV_PYTHON: ${{ matrix.python }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7

      - name: Install ffmpeg for video tests
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Setup test suite
        run: uv run --locked --only-group dev tox run -v --notest --skip-missing-interpreters false -e test

      # Run all tests on schedule, but only non-slow tests on push
      - name: Run pytest
        run: |
          if [ "${{ github.event_name }}" == "schedule" ]; then
            uv run --locked --only-group dev tox -e test
          else
            uv run --locked --only-group dev tox -e test -- -m "not slow"
          fi
        shell: bash # this wouldn't work on Powershell

      - name: Upload coverage reports to Codecov
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.python == '3.14' }}
        uses: codecov/codecov-action@v7.0.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  cli:
    name: CLI smoke tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Test transforms CLI tool
        run: uv run --locked -- torchio transform --help

      - name: Test info CLI tool
        run: uv run --locked -- torchio info --help

  docs:
    name: Documentation snippet tests
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Run doc snippet tests
        run: uv run --locked --only-group dev tox -e docs-test
